### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [kilpert3/TacticsDT#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by kilpert3** [comment]
Hi, this project is essentially my own studying based on another project by
Johnathan Parham at this link
https://theliquidfire.com/2015/05/04/tactics-rpg-series-intro/
His code is released under MIT license, so mine would be the same, as much
of it is reused from his project. In fact, I would highly recommend
checking out his blog and repository if you are interested in developing
this type of game instead of my own, as they are more cleanly written and
documented to help with the learning process.

-Tgood

**Comment by suprafun** [comment]
Thank you so very much.
